server:
  port: 8001

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  application:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    name: gateway-service
spring:
  cloud:
    gateway:
      routes:
        # 주문 서비스
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
              - Path=/order-service/**
          filters:
              - CustomFilter
              - RewritePath=/order-service/(?<segment>.*), /$\{segment}

        # 상품 서비스
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
              - Path=/product-service/**
          filters:
            - CustomFilter
            - RewritePath=/product-service/(?<segment>.*), /$\{segment}

        # 유저 서비스
        # 로그인
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/user/login
            - Method=POST
          #            - Path=/auth/**
          filters:
#            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - CustomFilter

        # 유저 서비스
        # 회원가입
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/user/signup
            - Method=POST
          filters:
            - RewritePath=/user/(?<segment>.*), /$\{segment}
            - CustomFilter

        # 유저 서비스
        # 다른 기능
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/user/**
            - Method=GET
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - CustomFilter

        # 유저 서비스
        # actuator
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/actuator/**
            - Method=GET,POST
          filters:
            - CustomFilter
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: 진짜 너무 어려운 것
            preLogger: true
            postLogger: true
#  jwt:
#    # HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용
#    secret: testSecretKey20240316testSecretKey20240316testSecretKey20240316
#    token:
#      access-expiration-time: 3600000
#      refresh-expiration-time: 86400000

management:
  endpoints:
    web:
      exposure:
        include: "health,info,refresh,beans,busrefresh"