server:
  port: 8001

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  application:
    name: gateway-service
spring:
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://PRODUCT-SERVICE  # 상품 직접 경로  (안됨)
          predicates:
            - Path=/product/**
          filters:
            - CustomFilter

        - id: user-service
          uri: lb://USER-SERVICE  # 상품 직접 경로  (안됨)
          predicates:
            - Path=/user/**
#            - Path=/auth/**
          filters:
            - CustomFilter
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: 진짜 너무 어려운 것
            preLogger: true
            postLogger: true

