server:
  port: 8081  # ????? ??????? ??

eureka:
  client:
    register-with-eureka: true       # Eureka ??? ?????? ??
    fetch-registry: true             # Eureka ????? ????? ????
    service-url:
      defaultZone: http://admin:1234@localhost:8761/eureka/  # ??? ?? ?? ??? URL

spring:
  cloud:
    config:
      enabled: false