server:
  port: 0 # using random port for load balancing hehe



eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true       # Eureka ??? ?????? ??
    fetch-registry: true             # Eureka ????? ????? ????
    service-url:
      defaultZone: http://admin:1234@127.0.0.1:8761/eureka/  # ??? ?? ?? ??? URL

spring:
  application:
    name: user-service
  cloud:
    config:
      enabled: false