
server:
  port: 0

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true       # Eureka ??? ?????? ??
    fetch-registry: true             # Eureka ????? ????? ????
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka  # ??? ?? ?? ??? URL

spring:
  application:
    name: order-service
  profiles:
    active: native
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      enabled: true

  # MYSQL DB setting
  datasource:
    url: jdbc:mysql://localhost:3306/rushorder
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # ???? ????? ?? ???? ??
      generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

logging:
  level:
    com.order.orderservice: DEBUG



management:
  endpoints:
    web:
      exposure:
        include: "*"