server:
  port: 8081



eureka:
  client:
    register-with-eureka: true       # Eureka ??? ?????? ??
    fetch-registry: true             # Eureka ????? ????? ????
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka  # ??? ?? ?? ??? URL

spring:
  application:
    name: product-service
  cloud:
    config:
      enabled: false