server:
  port: 0

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true       # Eureka ??? ?????? ??
    fetch-registry: true             # Eureka ????? ????? ????
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka  # ??? ?? ?? ??? URL

spring:
  application:
    name: product-service
  cloud:
    config:
      enabled: false
  sql:
    init:
      mode: always  # 항상 SQL 파일을 실행

  # MYSQL DB setting
  datasource:
    url: jdbc:mysql://localhost:3306/rushproduct
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # 컨테이너 환경에서도 자동 업데이트 사용
      generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    defer-datasource-initialization: true
  data:
    redis:
      host: localhost
      port: 6379


logging:
  level:
    com.order.productservice: DEBUG
