server:
  port: 8888

spring:
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/Desktop/config-client/native
        git:
#          uri: file:///C:/Users/Hans/Desktop/config-client/rush-msa
          uri: https://github.com/woojinhong/spring-cloud-config.git  # public repo 학습용 설정


  application:
    name: config-server
  profiles:
    active: native
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh, health"
